profiles/urls.py
from .views import ProfileDetailView

from django.conf.urls import url

urlpatterns = [
    url(r'^(?P<username>[\w-]+)/$',ProfileDetailView.as_view(),name="detail"),    
]

school/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import LoginView,LogoutView
from profiles.views import ProfileFollowToggle, RegisterView,activate_user_view
from teachers.views import HomeView
from django.views.generic import TemplateView
from eschool import views as eschool_views



urlpatterns = [
    
    url(r'^admin/', admin.site.urls),
    url(r'^home/$',HomeView.as_view(),name="home"),
    url(r'^about/$',TemplateView.as_view(template_name='about.html'),name="about"),
    url(r'^$',LoginView.as_view(), name="login"),
    url(r'^contact/$',TemplateView.as_view(template_name='contact.html'),name="contact"),
    url(r'^exams/', include('teachers.urls',namespace="teachers")),
    url(r'^attendance/', include('attendance.urls',namespace="attendance")),
    url(r'^continuous/', include('continuous.urls',namespace="continuous")),
    url(r'^students/', include('students.urls',namespace="students")),
    url(r'^logout/$',LogoutView.as_view(), name="logout"),
    url(r'^activate/(?P<code>[a-z0-9].*)/$',activate_user_view, name='activate'),
    url(r'^register/$',RegisterView.as_view(), name="register"),
    url(r'^profile-follow/$',ProfileFollowToggle.as_view(),name="follow"),
    url(r'^u/', include('profiles.urls',namespace="profiles")),
    
    
    
]

teachers/urls.py
from django.conf.urls import url,include
from .views import (ExamMarkListView,
                    ExamMarkCreateView,
                    ExamMarkDetailView,
                    ExamMarkUpdateView,
                    
                    )
    

urlpatterns = [
    
    url(r'^(?P<pk>\d+)/$',ExamMarkDetailView.as_view(),name="exams-detail"),
    url(r'^list/$', ExamMarkListView.as_view(),name="examlist"),
    url(r'^create/$',ExamMarkCreateView.as_view(),name="addmark"),
    url(r'^(?P<pk>\d+)/$',ExamMarkUpdateView.as_view(),name="updatem"),
    url(r'^(?P<pk>\d+)/update/$',ExamMarkUpdateView.as_view(),name="update"), 
    
    
    
]

teachers/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db.models import Q

from eschool.models import Student
User=settings.AUTH_USER_MODEL

class Marks(models.Model):
    user=models.ForeignKey(User)
    student_number=models.ForeignKey(Student)
    subject_name=models.CharField(max_length=50)
    Total_Mark=models.IntegerField()
    comment=models.TextField(max_length=200)
    slug=models.SlugField(null=True, blank=True)
    name=models.CharField(max_length=200)
    surname=models.CharField(max_length=40)

class ExamMarkQuerySet(models.query.QuerySet):
    def search(self,query):
        if query:
            query=query.strip()
            return self.filter(Q(student_number__icontains=query)
                               ).distinct()
        return self
class ExamMarkManager(models.Manager):
    def get_queryset(self):
        return ExamMarkQuerySet(self.model,using=self._db)
        
    def search(self,query):
        return self.get_queryset().search(query)
    
    
   
class ExamMark(Marks):
    
    paper1_Mark=models.IntegerField(null=True,blank=True)
    paper2_Mark=models.IntegerField(null=True, blank=True)
    paper3_Mark=models.IntegerField(null=True, blank=True)
    paper4_Mark=models.IntegerField(null=True, blank=True)
    paper5_Mark=models.IntegerField(null=True, blank=True)
    paper6_Mark=models.IntegerField(null=True, blank=True)
    objects=ExamMarkManager()
    def __str__(self):
        return self.student_number


    def get_absolute_url(self):
        return reverse('teachers:detail', kwargs={'pk':self.pk})
    def get_absolute_url(self):
        return reverse('teachers:update', kwargs={'pk':self.pk})


    
# Create your models here.

teachers/forms.py
from django import forms
from .models import ExamMark

class ExamMarkForm(forms.ModelForm):
    class Meta:
        
        model=ExamMark
        fields=[
            'student_number',
            'subject_name',
            'Total_Mark',
            'comment',
            'paper1_Mark',
            'paper2_Mark',
            'paper3_Mark',
            'paper4_Mark',
            'paper5_Mark',
            'paper6_Mark',
             ]
    def __init__(self,user=None,*args,**kwargs):
        #print(kwargs.pop('user'))
        print(user)
        #print(kwargs.pop('instance'))
        super(ExamMarkForm,self).__init__(*args,**kwargs)
         
    

                

teachers/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import ExamMarkForm
from .models import ExamMark
from django.views.generic import ListView,DetailView,CreateView,UpdateView,View

class HomeView(View):
    def get(self,request,*args,**kwargs):
        #if not request.user.is_authenticated():
        return render(request, "teachers/home.html",{})
        #user=request.user
        
        #is_following_user_ids=[x.user.id for x in user.is_following.all()]
        #qs=ExamMark.objects.filter(user__id__in=is_following_user_ids).order_by("student_number")[:5]
        #for x in user.is_following.all():
            #return render(request, "teachers/home-feed.html",{"object_list":qs})

class ExamMarkListView(ListView):
    def get_queryset(self):
        return ExamMark.objects.filter(user=self.request.user)
    
class ExamMarkDetailView(DetailView):
    def get_queryset(self):
        return ExamMark.objects.filter(user=self.request.user)
    
    
class ExamMarkCreateView(LoginRequiredMixin,CreateView):
    form_class=ExamMarkForm
    login_url='/login/'
    template_name="teachers/forms.html"
    success_url="/"
    def get_queryset(self):
        return ExamMark.objects.filter(user=self.request.user)
    def get_context_data(self,*args,**kwargs):
        context=super(ExamMarkCreateView,self).get_context_data(*args,**kwargs)
        context['title']='Add Exam Marks'
        return context
    def form_valid(self, form):
        obj=form.save(commit=False)
        obj.user=self.request.user
        return super(ExamMarkCreateView,self).form_valid(form)
    def get_form_kwargs(self):
        kwargs=super(ExamMarkCreateView,self).get_form_kwargs()
        kwargs['user']=self.request.user
        return kwargs

    
    
class ExamMarkUpdateView(LoginRequiredMixin,UpdateView):
    template_name="teachers/detail-update.html"
    form_class=ExamMarkForm
    def get_queryset(self):
        return ExamMark.objects.filter(user=self.request.user)
    def get_context_data(self,*args,**kwargs):
        context=super(ExamMarkUpdateView,self).get_context_data(*args,**kwargs)
        context['title']='Update Exam Marks'
        return context
    def get_form_kwargs(self):
        kwargs=super(ExamMarkUpdateView,self).get_form_kwargs()
        kwargs['user']=self.request.user
        return kwargs




# Create your views here.

teachers/templates/teachers/change_form.html
{% extends "base_site.html" %}
{% load i18n admin_urls static admin_modify %}

{% block extrahead %}{{ block.super }}
<script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
{{ media }}
{% endblock %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />{% endblock %}

{% block coltype %}colM{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} change-form{% endblock %}

{% if not is_popup %}
{% block breadcrumbs %}

{% endblock %}
{% endif %}

{% block content %}<div id="content-main">
{% block object-tools %}
{% if change %}{% if not is_popup %}
  <ul class="object-tools">
    {% block object-tools-items %}
    <li>
        {% url opts|admin_urlname:'history' original.pk|admin_urlquote as history_url %}
        <a href="{% add_preserved_filters history_url %}" class="historylink">{% trans "History" %}</a>
    </li>
    {% if has_absolute_url %}<li><a href="{{ absolute_url }}" class="viewsitelink">{% trans "View on site" %}</a></li>{% endif %}
    {% endblock %}
  </ul>
{% endif %}{% endif %}
{% endblock %}
<form {% if has_file_field %}enctype="multipart/form-data" {% endif %}action="{{ form_url }}" method="post" id="{{ opts.model_name }}_form" novalidate>{% csrf_token %}{% block form_top %}{% endblock %}
<div>
{% if is_popup %}<input type="hidden" name="{{ is_popup_var }}" value="1" />{% endif %}
{% if to_field %}<input type="hidden" name="{{ to_field_var }}" value="{{ to_field }}" />{% endif %}
{% if save_on_top %}{% block submit_buttons_top %}{% submit_row %}{% endblock %}{% endif %}
{% if errors %}
    <p class="errornote">
    {% if errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
    </p>
    {{ adminform.form.non_field_errors }}
{% endif %}

{% block field_sets %}
{% for fieldset in adminform %}
  {% include "admin/includes/fieldset.html" %}
{% endfor %}
{% endblock %}

{% block after_field_sets %}{% endblock %}

{% block inline_field_sets %}
{% for inline_admin_formset in inline_admin_formsets %}
    {% include inline_admin_formset.opts.template %}
{% endfor %}
{% endblock %}

{% block after_related_objects %}{% endblock %}

{% block submit_buttons_bottom %}{% submit_row %}{% endblock %}

{% block admin_change_form_document_ready %}
    <script type="text/javascript"
            id="django-admin-form-add-constants"
            src="{% static 'admin/js/change_form.js' %}"
            {% if adminform and add %}
                data-model-name="{{ opts.model_name }}"
            {% endif %}>
    </script>
{% endblock %}

{# JavaScript for prepopulated fields #}
{% prepopulated_fields_js %}

</div>
</form></div>
{% endblock %}

teachers/templates/teachers/deltaexams.html
{% extends "base_site.html"%}
{%block head_title%} Subjects ||{{block.super}}{%endblock head_title%}



{%block content %}
<h1> ExamMarks</h1>



<table border="1" cellpadding="1">

<th >student number</th>
<th>subject_ID</th>
<th>paper1_Mark</th>
<th>papert2_Mark</th>
<th>paper3_Mark</th>
<th>paper4_Mark</th>
{% for obj in object_list%}

<tr>
<td><a href='{{obj.get_absolute_url}}'>{{obj.student_number}}</a></td>
<td>{{obj.subject_ID}}</td>
<td>{{obj.paper1_Mark}}</td>
<td>{{obj.paper2_Mark}}</td>
<td>{{obj.paper3_Mark}}</td>
<td>{{obj.paper4_Mark}}</td>

</tr>
{%endfor%}
</table>
{%endblock content%}

teachers/templates/teachers/detail-update.html
{% extends "change_form.html"%}
{%block head_title%} {{form.instance.student_number}} ||{{block.super}}{%endblock head_title%}



{%block content %}
<h2>{{object.student_number}} </h2>
<h3>{{object.subject_name}}</h3>
<hr/>
<h3> make changes </h3>
{%include 'snippets/form_snippets.html' with form=form%}
{%endblock content%}

teachers/templates/teachers/exammark_detail.html
{% extends "base_site.html"%}
{%block head_title%} {{title }}||{{block.super}}{%endblock head_title%}



{%block content %}
<h2> {{object.student_number}}</h2>
<h3>{{object.subject_ID}}</h3>
{%endblock content%}

teachers/templates/teachers/exammark_list.html
{% extends "base_site.html"%}
{%block head_title%} Subjects ||{{block.super}}{%endblock head_title%}



{%block content %}
<h1> Examination Marks</h1>



<table border="1" cellpadding="1">

<th >student number</th>
<th>subject name</th>
<th>paper1 Mark</th>
<th>papert2 Mark</th>
<th>paper3 Mark</th>
<th>paper4 Mark</th>
<th>paper5 Mark</th>
<th>paper6 Mark</th>
<th>Total Mark</th>
<th>comment </th>
{% for obj in object_list%}

<tr>
<td><a href='{{obj.get_absolute_url}}'>{{obj.student_number}}</a></td>
<td>{{obj.subject_name}}</td>
<td>{{obj.paper1_Mark}}</td>
<td>{{obj.paper2_Mark}}</td>
<td>{{obj.paper3_Mark}}</td>
<td>{{obj.paper4_Mark}}</td>
<td>{{obj.paper5_Mark}}</td>
<td>{{obj.paper6_Mark}}</td>
<td>{{obj.Total_Mark}}</td>
<td>{{obj.comment}}</td>

</tr>
{%endfor%}
</table>
{%endblock content%}

teachers/templates/teachers/forms.html
{% extends "change_form.html"%}
{%block head_title%} Add Exam Marks ||{{block.super}}{%endblock head_title%}


{%block content %}

{%if form.errors.non_field_errors %}
{{form.errors.non_field_errors}}
{% endif %}


<div id="content-main">
<form method="POST">
<fieldset class="module aligned wide">

{% csrf_token %}


 {{form.as_p}}
 
 <center>
<input type="submit" value="Add"></br>
</center>


</form>

</div>
</fieldset>
{%endblock %}

teachers/templates/teachers/home-feed.html
{% extends "base.html"%}

{%block content %}
{% for obj in object_list %}
<h1><a href='{% url "profiles:detail" username=obj.user.username %}'>{{obj.user.username}}</a></h1>
{% endfor%}
<table border="1">
<th> studentnumber</th>
<th>subject_ID</th>
<th>paper1_Mark</th>
<th>paper2_Mark</th>
<th>paper3_Mark</th>
<th>paper4_Mark</th>
{% for obj in object_list%}

<tr>
<td><a href='{% url "profiles:detail" username=obj.user.username %}?q={{obj.student_number}}'>{{obj.student_number}}</a></td>
<td>{{obj.subject_ID}}</td>
<td>{{obj.paper1_Mark}}</td>
<td>{{obj.paper2_Mark}}</td>
<td>{{obj.paper3_Mark}}</td>
<td>{{obj.paper4_Mark}}</td>
</tr>

{% endfor%}



</table>





{%endblock content%}

teachers/templates/teachers/home.html
{% extends "base_site.html"%}
{%block head_title%} Subjects ||{{block.super}}{%endblock head_title%}



{%block content %}
<h1>Attendance</h1>

<table border="1" cellpadding="1">


<th>date</th>
<th>status</th>
<th>reason_of_absence</th>


{% for obj in object_list%}

<tr>

<td>{{obj.date}}</td>
<td>{{obj.status}}</td>
<td>{{obj.reason_of_absence}}</td>


</tr>
{%endfor%}
</table>

{%endblock content%}

teachers/templates/teachers/index.html
{% extends "base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}" />{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
<div id="content-main">

{% if app_list %}
    {% for app in app_list %}
        <div class="app-{{ app.app_label }} module">
        <table>
        <caption>
            <a href="{{ app.app_url }}" class="section" title="{% blocktrans with name=app.name %}Models in the {{ name }} application{% endblocktrans %}">{{ app.name }}</a>
        </caption>
        {% for model in app.models %}
            <tr class="model-{{ model.object_name|lower }}">
            {% if model.admin_url %}
                <th scope="row"><a href="{{ model.admin_url }}">{{ model.name }}</a></th>
            {% else %}
                <th scope="row">{{ model.name }}</th>
            {% endif %}

            {% if model.add_url %}
                <td><a href="{{ model.add_url }}" class="addlink">{% trans 'Add' %}</a></td>
            {% else %}
                <td>&nbsp;</td>
            {% endif %}

            {% if model.admin_url %}
                <td><a href="{{ model.admin_url }}" class="changelink">{% trans 'Change' %}</a></td>
            {% else %}
                <td>&nbsp;</td>
            {% endif %}
            </tr>
        {% endfor %}
        </table>
        </div>
    {% endfor %}
{% else %}
    <p>{% trans "You don't have permission to edit anything." %}</p>
{% endif %}
</div>
{% endblock %}

{% block sidebar %}
<div id="content-related">
    <div class="module" id="recent-actions-module">
        <h2>{% trans 'Recent actions' %}</h2>
        <h3>{% trans 'My actions' %}</h3>
            {% load log %}
            {% get_admin_log 10 as admin_log for_user user %}
            {% if not admin_log %}
            <p>{% trans 'None available' %}</p>
            {% else %}
            <ul class="actionlist">
            {% for entry in admin_log %}
            <li class="{% if entry.is_addition %}addlink{% endif %}{% if entry.is_change %}changelink{% endif %}{% if entry.is_deletion %}deletelink{% endif %}">
                {% if entry.is_deletion or not entry.get_admin_url %}
                    {{ entry.object_repr }}
                {% else %}
                    <a href="{{ entry.get_admin_url }}">{{ entry.object_repr }}</a>
                {% endif %}
                <br/>
                {% if entry.content_type %}
                    <span class="mini quiet">{% filter capfirst %}{{ entry.content_type }}{% endfilter %}</span>
                {% else %}
                    <span class="mini quiet">{% trans 'Unknown content' %}</span>
                {% endif %}
            </li>
            {% endfor %}
            </ul>
            {% endif %}
    </div>
</div>
{% endblock %}