attendance/urls.py
from django.conf.urls import url,include
from .views import (AttendanceListView,
                    AttendanceCreateView,
                    AttendanceDetailView,
                    AttendanceUpdateView,
                   
                    )
    

urlpatterns = [
    
    url(r'^(?P<pk>\d+)/$',AttendanceDetailView.as_view(),name="attendance-detail"),
    url(r'^$', AttendanceListView.as_view(),name="attendancelist"),
    url(r'^create/$',AttendanceCreateView.as_view(),name="addattendance"),
    url(r'^(?P<pk>\d+)/update/$',AttendanceUpdateView.as_view(),name="updateattendance"),
    
    
    
]

continuous/urls.py
from django.conf.urls import url,include
from .views import (
                    Continuous_AssessmentListView,
                    Continuous_AssessmentDetailView,
                    Continuous_AssessmentCreateView,
                    Continuous_AssessmentUpdateView
                    )
    

urlpatterns = [
    
        
    
    url(r'^(?P<pk>\d+)/update$',Continuous_AssessmentUpdateView.as_view(),name="update"), 
    url(r'^$', Continuous_AssessmentListView.as_view(),name="listcontinuous"),
    url(r'^create/$',Continuous_AssessmentCreateView.as_view(),name="addcontinuous"),
    url(r'^(?P<pk>\d+)/$',Continuous_AssessmentDetailView.as_view(),name="detail")
    
    
]

school/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import LoginView,LogoutView
from profiles.views import ProfileFollowToggle, RegisterView,activate_user_view
from teachers.views import HomeView
from django.views.generic import TemplateView
from eschool import views as eschool_views



urlpatterns = [
    
    url(r'^admin/', admin.site.urls),
    url(r'^home/$',HomeView.as_view(),name="home"),
    url(r'^about/$',TemplateView.as_view(template_name='about.html'),name="about"),
    url(r'^$',LoginView.as_view(), name="login"),
    url(r'^contact/$',TemplateView.as_view(template_name='contact.html'),name="contact"),
    url(r'^exams/', include('teachers.urls',namespace="teachers")),
    url(r'^attendance/', include('attendance.urls',namespace="attendance")),
    url(r'^continuous/', include('continuous.urls',namespace="continuous")),
    url(r'^students/', include('students.urls',namespace="students")),
    url(r'^logout/$',LogoutView.as_view(), name="logout"),
    url(r'^activate/(?P<code>[a-z0-9].*)/$',activate_user_view, name='activate'),
    url(r'^register/$',RegisterView.as_view(), name="register"),
    url(r'^profile-follow/$',ProfileFollowToggle.as_view(),name="follow"),
    url(r'^u/', include('profiles.urls',namespace="profiles")),
    
    
    
]

students/urls.py
from django.conf.urls import url,include
from .views import (
                    Continuous_AssessmentListView,
                    AttendanceListView,
                    ExamMarkListView,
                    FeeListView,
                    BorrowingListView,
                    HostelListView
                
                    
                    
                    
                    )
    

urlpatterns = [
    
        
    url(r'^$', Continuous_AssessmentListView.as_view(),name="studentscontinuous"),
    url(r'^attendance/$', AttendanceListView.as_view(),name="attendance"),
    url(r'^exammark/$', ExamMarkListView.as_view(),name="exammark"),
    url(r'^fees/$', FeeListView.as_view(),name="fees"),
    url(r'^borrowing/$', BorrowingListView.as_view(),name="borrowing"),
    url(r'^hostel/$', HostelListView.as_view(),name="hostel"),
    
   
    
    
]

teachers/urls.py
from django.conf.urls import url,include
from .views import (ExamMarkListView,
                    ExamMarkCreateView,
                    ExamMarkDetailView,
                    ExamMarkUpdateView,
                    
                    )
    

urlpatterns = [
    
    url(r'^(?P<pk>\d+)/$',ExamMarkDetailView.as_view(),name="exams-detail"),
    url(r'^list/$', ExamMarkListView.as_view(),name="examlist"),
    url(r'^create/$',ExamMarkCreateView.as_view(),name="addmark"),
    url(r'^(?P<pk>\d+)/$',ExamMarkUpdateView.as_view(),name="updatem"),
    url(r'^(?P<pk>\d+)/update/$',ExamMarkUpdateView.as_view(),name="update"), 
    
    
    
]

eschool/models.py
from django.db import models
from django.db import models

class People (models.Model):
    
    firstname=models.CharField(max_length=50)
    lastname=models.CharField(max_length=50)
    Phonenumber=models.CharField(max_length=10)
    Physical_Address=models.TextField(max_length=200)
    Email_Address=models.EmailField(max_length=254, null=True, blank=True)
    Image=models.FileField(upload_to='uploads/')
    DOB=models.DateField()
    class Meta:
        abstract=True
class Subject(models.Model):
    subject_name=models.CharField(max_length=20)
    subject_ID=models.CharField(max_length=20,primary_key=True,unique=True)
    def __str__(self):
        return self.subject_ID
class Teacher(People):
    
    EmploymentID=models.CharField(max_length=50, primary_key=True,unique=True)
    subject_ID=models.ForeignKey(Subject,on_delete=models.CASCADE)
    def __str__(self):
        return self.EmploymentID
class Student(People):
    student_number=models.CharField(max_length=50, primary_key=True,unique=True)
    def __str__(self):
        return self.student_number
    
class Parent(People):
    NID=models.CharField(max_length=50, unique=True)
    position=models.CharField(max_length=50)
    student_number=models.ManyToManyField(Student)
    landline_number=models.CharField(max_length=50)
    occupation=models.CharField(max_length=50)
    def __str__(self):
        return self.lastname

class Hostel(models.Model):
    hostel_ID=models.CharField(max_length=20,primary_key=True)
    hostel_name=models.CharField(max_length=20)
    student_number=models.ForeignKey(Student,on_delete=models.CASCADE)
    def __str__(self):
        return self.hostel_ID
class Fee(models.Model):
    Amount_paid=models.DecimalField(max_digits=5, decimal_places=2)
    student_number=models.ForeignKey(Student,on_delete=models.CASCADE)
    invoice_number=models.CharField(max_length=50)
    tutoring_fee=models.DecimalField(max_digits=5, decimal_places=2)
    Bank_name=models.CharField(max_length=50)
class Book(models.Model):
    book_number=models.CharField(max_length=50,primary_key=True,unique=True)
    published_date=models.DateField()
    Author=models.CharField(max_length=50)
    book_title=models.CharField(max_length=50)
    def __str__(self):
        return self.book_number
class Borrowing(models.Model):
    book_number=models.CharField(max_length=50,primary_key=True)
    book_title=models.CharField(max_length=50)
    student_number=models.ForeignKey(Student,on_delete=models.CASCADE)
    date_taken=models.DateField()
    return_date=models.DateField()


   
                     

     
    

    
    

# Create your models here.


# Create your models here.

eschool/views.py
from django.shortcuts import render
def index(request):
    return render(request, 'eschool/parents.html')

# Create your views here.

eschool/templates/snippets/form_snippets.html
{% extends "change_form.html"%}
{%block head_title%} Add Subjects ||{{block.super}}{%endblock head_title%}

{%block content %}
<h1> {{title}}</h1>
{%if form.errors.non_field_errors %}
{{form.errors.non_field_errors}}
{% endif %}

<form method="POST">
<fieldset class="module aligned wide">
{% csrf_token %}
<!--Student Number:</br><input name="student_number" type="text"></br>
Subject_ID:</br><input name="subject_ID" type="text"></br>
 Mark: </br><input name="Total_Mark" type="text"></br>-->
 {{form.as_p}}
 <center>
<input type="submit" value="add">
</center>

</form>
<fieldset>
{%endblock %}

eschool/templates/snippets/nav.html
<div class="container">
<a href='{%url "home" %}'>home |</a>
<a href='{%url "about" %}'>about |</a>
<a href='{%url "contact" %}'>contact |</a>
{% if request.user.is_authenticated %}
{% if request.user.is_staff %}
<a href='{%url "teachers:examlist" %}'>view marks| </a>
<a href='{%url "teachers:addmark" %}'>Add Exam Marks |</a>
<a href='{%url "continuous:listcontinuous" %}'>view coursework |</a>
<a href='{%url "continuous:addcontinuous" %}'>Add coursework |</a>
<a href='{%url "attendance:attendancelist" %}'>view attendance |</a>
<a href='{%url "attendance:addattendance" %}'>Add attendance |</a>
<a href='{%url "register" %}'>register|</a>
<a href='{%url "logout" %}'> logout|</a>
{% else %}
<a href='{%url "students:studentscontinuous" %}'>view coursework| </a>
<a href='{%url "students:exammark" %}'>view Exams |</a>
<a href='{%url "students:attendance" %}'>view attendance |</a>
<a href='{%url "students:fees" %}'>view fees |</a>
<a href='{%url "students:hostel" %}'>view hostel |</a>
<a href='{%url "students:borrowing" %}'>Library Information |</a>
<a href='{%url "logout" %}'> logout|</a>
{% endif %}
{% endif %}

</div>

eschool/templates/snippets/navigate.html
<div class="container">
<a href='{%url "home" %}'>home |</a>
<a href='{%url "about" %}'>about |</a>
<a href='{%url "contact" %}'>contact |</a>
{% if request.user.is_authenticated %}
<a href='{%url "students:studentscontinuous" %}'>view Results| </a>
<a href='{%url "students:fees" %}'>view fees |</a>
<a href='{%url "students:attendance" %}'>view attendance |</a>
<a href='{%url "logout" %}'> logout|</a>
{% endif %}




</div>

eschool/templates/snippets/navigation.html
 <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
				  <li><a href='{%url "home" %}'>home |</a></li>
                  <li><a href='{%url "about" %}'>about |</a></li>
                  <li><a href='{%url "contact" %}'>contact |</a></li>
				  
                  {% if request.user.is_authenticated %}
                   <li><a href='{%url "teachers:examlist" %}'>view marks| </a></li>
                   <li><a href='{%url "teachers:addmark" %}'>Add Exam Marks |</a></li>
                   <li><a href='{%url "continuous:listcontinuous" %}'>view coursework |</a></li>
                   <li><a href='{%url "continuous:addcontinuous" %}'>Add coursework |</a></li>
                   <li> <a href='{%url "attendance:attendancelist" %}'>view attendance |</a></li>
                   <li><a href='{%url "attendance:addattendance" %}'>Add attendance |</a></li>
				   <li><a href='{%url "register" %}'>register|</a></li>

                   {%endif%}
                 <!--- <li><a href="index.html">Examination Results</a></li>
				  <li><a href="index.html">Continuous Assessment</a></li>
				  <li><a href="index.html">Exam Timetable</a></li>
				  <li><a href="index.html">Announcements</a></li>
				  <li><a href="index.html">View Prefects</a></li>
				  <li><a href="index.html">View Fees Payment</a></li>
				  <li><a href="index.html">view Calender</a></li>
				   <li><a href="index.html">Edit password/email</a></li>-->
				  </ul>
              </div>
</div>